josedamLit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include ('josepdam.urls')),
    path ('memberAccount/',include ('django.contrib.auth.urls')),
    path ('memberAccount/',include ('memberAccount.urls')), 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

josepdam/urls.py
from django.urls import path
from . import views 
from .views import HomeView, ArticleDetailView, TeamView, ArticleTeamDetailView, TeamDirectorView,BlogView,AboutView
from .views import ArticleBoardOfDirectorDetailView, BlogArticleDetailView,SecondConstructionDetailViewArticleDetailView


urlpatterns = [
    path('base/', views.base, name='base'),
    path('', HomeView.as_view(), name="home"),
    path('home/', HomeView.as_view(), name='home'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name="detail"),
    path('article2/<int:pk>/', SecondConstructionDetailViewArticleDetailView.as_view(), name="second_detail"),
    path('about/', AboutView.as_view(), name='about'),
    path('our_services/', views.OurServices, name='our_services'),
    path('blog/', BlogView.as_view(), name="blog"),
    path('article_blog/<int:pk>/', BlogArticleDetailView.as_view(), name="detail-blog"),
    path('contact/', views.contact, name='contact'),
    path('video/', views.video, name='video'),
    path('our_projects/', views.OurProjects, name='our_projects'),
    path('message/', views.message, name='message'),
    path('team/', TeamView.as_view(), name='team'),
    path('article_team/<int:pk>/', ArticleTeamDetailView.as_view(), name="detail-team"),
    path('director/', TeamDirectorView.as_view(), name='director'),
    path('article_board_of_director/<int:pk>/', ArticleBoardOfDirectorDetailView.as_view(), name="detail-director"),
    #path('post/<int:post_id>/like/', views.like_post, name='post-detail'),
    path('article/<int:post_id>/like/', views.like_post, name='like-post'),

   

]

josepdam/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date

#The search button model of locatin
    
# The main Josepdam Model
class ConstructionPost(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    slug = models.SlugField (max_length=255)
    img = models.ImageField ( upload_to= 'image/')
    publish_date = models.DateTimeField (auto_now_add= True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    rent = models.CharField(max_length = 50,blank=True, null=True)
    size = models.CharField(max_length = 50,blank=True, null=True)
    details = models.CharField(max_length = 200,blank=True, null=True)
    location = models.CharField(max_length = 200,blank=True, null=True)
    
    class Meta:
        ordering =['-publish_date']
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse ('home')
    

#The second main Josepdam Model
class SecondConstruction(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    slug = models.SlugField (max_length=255)
    image1 = models.ImageField ( upload_to= 'image3/')
    publish_date = models.DateTimeField (auto_now_add= True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    rent = models.CharField(max_length = 50,blank=True, null=True)
    details = models.CharField(max_length = 100,blank=True, null=True)
    location = models.CharField(max_length = 100,blank=True, null=True)
    
    class Meta:
        ordering =['-publish_date']
    
    def __str__(self):
        return self.title+ ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse ('home')
    

# The like and unlike model for each property
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(ConstructionPost, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
# The Josepdam team Model
class TeamsPost (models.Model):
    worker_name = models.CharField (max_length = 200, blank=True, null=True)
    worker_position = models.CharField (max_length = 200, blank=True, null=True)
    worker_description = models.TextField()
    worker_img = models.ImageField(upload_to='images')
    slug = models.SlugField (max_length=25)
    publish_date = models.DateTimeField (auto_now_add= True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering =['-publish_date']

    def get_absolute_url(self):
        return reverse ('home')
    
    def __str__(self):
        return self.worker_name + ' | ' + str(self.author)
    
# The josepdam board of director Model
class Board_Of_DirectorPost (models.Model):
    board_of_director_name = models.CharField (max_length = 200, blank=True, null=True)
    board_of_director_position = models.CharField (max_length = 210, blank=True, null=True)
    board_of_director_description = models.TextField()
    board_of_director_img = models.ImageField(upload_to='images_dir')
    slug = models.SlugField (max_length=25)
    publish_date = models.DateTimeField (auto_now_add= True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering =['-publish_date']

    def get_absolute_url(self):
        return reverse ('home')
    
    def __str__(self):
        return self.board_of_director_name + ' | ' + str(self.author)
    

# The blog post of Josepdam Model
class BlogPost(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    slug = models.SlugField (max_length=255)
    img = models.ImageField ( upload_to= 'image_blog/')
    publish_date = models.DateTimeField (auto_now_add= True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.CharField(max_length = 200,blank=True, null=True)
    
    

    class Meta:
        ordering =['-publish_date']
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse ('home')
    

class AboutMissionVisionCorevalues(models.Model):
    title = models.CharField(max_length=900, blank=True, null=True)
    description = models.TextField()

    def __str__(self):
        return self.title 

templates/josep/article_board_of_director.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.worker_name }} {% endblock %}
{% block content%}

    <!-- Page Content -->
    <div class="page-headinggg header-text">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h1> <small><del></small> <sup>$</sup>{{ object.price }}</h1>
              <span>{{ object.location }}</span>
            </div>
          </div>
        </div>
      </div>

    <div class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div>
              {% if object.board_of_director_img %}
              <img src="{{ object.board_of_director_img.url }}" alt="" class="img-fluid wc-image">
              {% endif %}
            </div> <br>
          </div>
        </div> <br>
        <div class="tabs-content" style="display: block;">
          <h3>{{ object.board_of_director_name }}</h3><br>
          <h5>{{ object.board_of_director_position }}</h5><br>
          <p>{{ object.board_of_director_description|truncatechars:9000 }}</p>
        </div> <hr>
        <span> 
           <a href="{% url 'director' %}" class="btn btn-info"><i class="fa fa-angle-left">Back</i></a>
            <!--<small>Posted: </small> {{ object.publish_date }} -->
        </span>
          <div class="col-lg-3">
            <div class="tabs-content">
             
            </div>
          </div>
        </div>
        <br>
        <br>
      </div>
    </div>



{% endblock %}

templates/josep/article_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.title }} {% endblock %}
{% block content%}

    <!-- Page Content -->
    <div class="page-headin header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2> <small><del></small> <sup></sup>  </h2>
            <span> </span><br>
            <a " " class="btn btn-blue"> </a>
          </div>
        </div>
      </div>
    </div>

    <div class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <div>
              {% if object.img %}
              <img src="{{ object.img.url }}" alt="" class="img-fluid wc-image">
              {% endif %}
            </div> <br>
          </div>
          
          <div class="col-md-5">
            <form action="#" method="post" class="form">
              <ul class="list-group list-group-flush">
               <li class="list-group-item">
                    <div class="clearfix">
                      <strong class="pull-left">Type :</strong>
                      <span class="pull-right">{{ object.title|truncatechars:14 }}</span>
                    </div>
               </li>

               <li class="list-group-item">
                    <div class="clearfix">
                         <strong class="pull-left">Rent :</strong>
                         <span class="pull-right"> {{ object.rent }}</span>
                    </div>
               </li>

               <li class="list-group-item">
                    <div class="clearfix">
                      <strong class="pull-left">Size :</strong>
                         <span class="pull-right">{{ object.size }}Sqm</span>
                    </div>
               </li>
                <li class="list-group-item">
                  <div class="clearfix">
                       <strong class="pull-left">Click Map :</strong>
                       <a href="https://www.google.com/maps/@6.5352339,3.3489682,15z?entry=ttu"> <strong class="pull-right"> Map</strong>
                       </div></a>
                  </li>
              </li>
              
           <li class="list-group-item">
            <div class="clearfix">
              <strong class="pull-left">Description :</strong>
              <span class="pull-right">{{ object.details }}</span>
            </div>
            <li class="list-group-item">
              <div class="clearfix">
                <strong class="pull-left">Location :</strong>
                <span class="pull-right">{{ object.location }}</span>
              </div>
         </li>
          </li>
        
        </div> <br>
        
        <div class="tabs-content" style="display: block;">
          <h4>{{ object.title }}</h4>
          <p>{{ object.description|truncatechars:9000 }}</p>
        </div>
        <span>
           <a href="{% url 'home' %}" class="btn btn-primary"><i class="fa fa-angle-left">Back</i></a>
           <a href="{% url 'contact' %}" class="btn btn-primary"><small>Info Us</small></a>
        </span>

          <div class="col-lg-3">
            <div class="tabs-content">
              
            </div>
          </div>
        </div>
        <br>
        <br>
        <br>
      </div>
    </div>

    <div id="map">

        <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=LAGOS+(asiness%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.maps.ie/population/">Calculate population in area</a></iframe></div>
    </div> 

{% endblock %}

templates/josep/article_team_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.worker_name }} {% endblock %}
{% block content%}

    <!-- Page Content -->
    <div class="page-headingdddddd header-text">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h1> <small><del></small> <sup>$</sup>{{ object.price }}</h1>
              <span>{{ object.location }}</span>
            </div>
          </div>
        </div>
      </div>

    <div class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div>
              {% if object.worker_img %}
              <img src="{{ object.worker_img.url }}" alt="" class="img-fluid wc-image">
              {% endif %}
            </div> <br>
          </div>
        </div> <br>
        <div class="tabs-content" style="display: block;">
          <h3>{{ object.worker_name }}</h3><br>
          <h6>{{ object.worker_position }}</h6><br>
          <p>{{ object.worker_description|truncatechars:9000 }}</p>
        </div> <hr>
        <span> 
           <a href="{% url 'team' %}" class="btn btn-info"><i class="fa fa-angle-left">Back</i></a>
            
        </span>
          <div class="col-lg-3">
            <div class="tabs-content">
             
            </div>
          </div>
        </div>
        <br>
        <br>
      </div>
    </div>



{% endblock %}

templates/josep/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %}The Blog Page{% endblock %}
{% block content%}

    <!-- Page Content -->
    <div class="page-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>Read our Blog</h1>
            <span>Josepdam Real Estate Properties Are For You</span>
          </div>
        </div>
      </div>
    </div>

    <div class="single-services">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <section class='tabs-content'>
              {% for post in object_list %} 

              <article id='tabs-2'>
                <a href="{% url 'detail-blog' post.pk %}">
                {% if post.img %}
                <img src="{{ post.img.url }}" alt=""
                {% endif %}
              </a>
              
              <h4><a href="{% url 'detail-blog' post.pk %}">{{ post.title|truncatechars:30 }}</a></h4>
                <div style="margin-bottom:10px;">
                  <span>Posted by: {{post.author}}&nbsp;|&nbsp; {{ post.publish_date }} &nbsp;|&nbsp;<span>
                </div>
                <p>{{ post.description|truncatechars:150 }}</p>
                <br>
                <div>
                  <a href="{% url 'detail-blog' post.pk %}" class="filled-button">Continue Reading</a>
                </div><br>
              </article>
              {% endfor %}
            </section>
          </div>

        </div>
      </div>
    </div>

    <br>  
    <br>  
    <br>  
  
    {% endblock %}

templates/josep/blog_article_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.title }}{% endblock %}
{% block content%}


    <!-- Page Content -->
    <div class="page-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>{{ object.title }}</h2><br>
            <span>Posted: <i class="fa fa-user"></i> {{ object.author }} &nbsp;|&nbsp; <i class="fa fa-calendar"></i> {{ object.publish_date }}</span>
          </div>
        </div>
      </div>
    </div>

    <div class="more-info about-info">
      <div class="container">
        <div class="more-info-content">
          <div class="right-content">
            <div>
              {% if object.img %}
              <img src="{{ object.img.url }}" class="img-fluid" alt="">
              {% endif %}
            </div>
            <br>
            <p> {{ object.description |truncatechars:9000}} </p>
          </div>
          <span> <a href="{% url 'blog' %}" class="btn btn-info"><i class="fa fa-angle-left">Back</i>
              </a>&nbsp;| Posted by: <i class="fa fa-user"></i> {{ object.author }} &nbsp;|&nbsp; <i class="fa fa-calendar"></i>
             {{ object.publish_date }}</span>
        </div><br>
      </div>
    </div>
            <!-- Something can go in here senwin-->
      </div>
    </div>

    <div id="map">

      <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=LAGOS+(asiness%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.maps.ie/population/">Calculate population in area</a></iframe></div>
  </div> 
    

   
    {% endblock %}

templates/josep/contact.html
{% extends "base.html" %}
{% load static %}
{% block title %} Contact JosepDam {% endblock %}
{% block content%}

    <!-- Page Content -->
    <div class="page-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>Talk to us</h1>
            <span>feel free to send us a message now and we'll get back to you..!</span>
          </div>
        </div>
      </div>
    </div>

    <div class="contact-information">
      <div class="container">
        <div class="row">
          <a href="https://wa.me/+2348106941149?text=Hi JosepDam ?">
          <div class="col-md-4">
            <div class="contact-item">
              <i class="fa fa-whatsapp"></i>
              <h4>Whatsapp</h4>
              <p>Send a message on whatsapp.</p>
              <a href="https://wa.me/+2348106941149?text=Hi JosepDam ?">View on Whatsapp</a>
            </div>
          </a>
          </div>

          <a href="mailto:info@josepdam.com">
          <div class="col-md-4">
            <div class="contact-item">
              <i class="fa fa-envelope"></i>
              <h4>Email/Info</h4>
              <p>Email us directly on gmail.</p>
              <a href="mailto:info@josepdam.com">View on Gmail</a>
            </div>
          </div>
         </a>

          <a href="https://maps.app.goo.gl/uNNsbrMFuA9V3HN36">
          <div class="col-md-4">
            <div class="contact-item">
              <i class="fa fa-map-marker"></i>
              <h4>Location</h4>
              <p>19 Fatai Atere way Mushin,Lagos Nigeria</p>
              <a href="https://maps.app.goo.gl/uNNsbrMFuA9V3HN36">View on Google Maps</a>
            </div>
          </div>
        </a>
        </div>
      </div>
    </div>

    <div class="callback-form contact-us">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Send us a <em>message</em></h2>
              <span>We'll get back to you before 24 hours..</span>
            </div>
          </div>
          <div class="col-md-12">
            <div class="contact-form">
              <form method="POST">
                {% csrf_token %}
                <div class="row">
                  <div class="col-lg-4 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="message-name" type="text" class="form-control" id="name" placeholder="Full Name" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-4 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="message-email" type="text" class="form-control" id="email" pattern="[^ @]*@[^ @]*" placeholder="E-Mail Address" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-4 col-md-12 col-sm-12">
                    <fieldset>
                      <input name="message-subject" type="text" class="form-control" id="subject" placeholder="Subject" required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your Message" required=""></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="filled-button">Send Message</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="map">
<!-- How to change your own map point
	1. Go to Google Maps
	2. Click on your location point
	3. Click "Share" and choose "Embed map" tab
	4. Copy only URL and paste it within the src="" field below
-->
      <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=19%20FATAI%20ATERE%20MUSHIN%20LAGOS+(asiness%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.maps.ie/population/">Calculate population in area</a></iframe></div>
    </div> 

{% endblock %}
   

templates/josep/index.html
{% extends "base.html" %}
{% load static %}

{% block content%}
    
    <!-- Banner Starts Here -->
    <div class="main-banner header-text" id="top">
        <div class="Modern-Slider">
          <!-- Item -->
          <div class="item item-1">
            <div class="img-fill">
                <div class="text-content">
                  <h6>lorem ipsum dolor sit amet!</h6>
                  <h4>Quam temporibus accusam <br> hic ducimus quia</h4>
                  <p>Magni deserunt dolorem consectetur adipisicins, omnis unde quae illo.</p>
                  <a href="properties.html" class="filled-button">Properties</a>
                </div>
            </div>
          </div>
          <!-- // Item -->
          <!-- Item -->
          <div class="item item-2">
            <div class="img-fill">
                <div class="text-content">
                  <h6>magni deserunt dolorem harum quas!</h6>
                  <h4>Aliquam iusto harum <br>  ratione porro odio</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At culpa cupiditate mollitia adipisci assumenda laborum eius quae quo excepturi, eveniet. Dicta nulla ea beatae consequuntur?</p>
                  <a href="about.html" class="filled-button">About Us</a>
                </div>
            </div>
          </div>
          <!-- // Item -->
          <!-- Item -->
          <div class="item item-3">
            <div class="img-fill">
                <div class="text-content">
                  <h6>alias officia qui quae vitae natus!</h6>
                  <h4>Lorem ipsum dolor <br>sit amet, consectetur.</h4>
                  <p>Vivamus ut tellus mi. Nulla nec cursus elit, id vulputate mi. Sed nec cursus augue. Phasellus lacinia ac sapien vitae dapibus. Mauris ut dapibus velit cras interdum nisl ac urna tempor mollis.</p>
                  <a href="contact.html" class="filled-button">Contact Us</a>
                </div>
            </div>
          </div>
          <!-- // Item -->
        </div>
    </div>
    <!-- Banner Ends Here -->


    <div class="request-form">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h4>Request a call back right now ?</h4>
            <span>Mauris ut dapibus velit cras interdum nisl ac urna tempor mollis.</span>
          </div>
          <div class="col-md-4">
            <a href="contact.html" class="border-button">Contact Us</a>
          </div>
        </div>
      </div>
    </div>



    <div class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Featured <em>Properties</em></h2>
              <span>Aliquam id urna imperdiet libero mollis hendrerit</span>
            </div>
          </div>
          <div class="col-md-4">
            <div class="service-item">
              <img src="{% static 'assets/images/product-1-720x480.jpg' %}" alt="">
              <div class="down-content">
                <h4>Lorem ipsum dolor sit amet</h4>
                <p>House hfhidhfd fuisnfiunsifjfsdf gdgdvsd</p>
                <a href="property-details.html" class="filled-button">View More</a>
              </div>
            </div>
            <br>
          </div>
        </div>
      </div>
    </div>



    <div class="fun-facts">
      <div class="container">
        <div class="more-info-content">
          <div class="row">
            <div class="col-md-6">
              <div class="left-image">
                <img src="{% static 'assets/images/about-1-570x350.jpg' %}" class="img-fluid" alt="">
              </div>
            </div>
            <div class="col-md-6 align-self-center">
              <div class="right-content">
                <span>Who we are</span>
                <h2>Get to know about <em>our company</em></h2>
                <p>Curabitur pulvinar sem a leo tempus facilisis. Sed non sagittis neque. Nulla conse quat tellus nibh, id molestie felis sagittis ut. Nam ullamcorper tempus ipsum in cursus</p>
                <a href="about.html" class="filled-button">Read More</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="more-info">
      <div class="container">
        <div class="section-heading">
          <h2>Read our <em>Blog</em></h2>
          <span>Aliquam id urna imperdiet libero mollis hendrerit</span>
        </div>
        <div class="row" id="tabs">
          <div class="col-md-4">
            <ul>
              <li><a href='#tabs-1'>Lorem ipsum dolor sit amet, consectetur adipisicing <br> <small>John Doe &nbsp;|&nbsp; 27.07.2020 10:10</small></a></li>
              <li><a href='#tabs-2'>Mauris lobortis quam id dictum dignissim <br> <small>John Doe &nbsp;|&nbsp; 27.07.2020 10:10</small></a></li>
            </ul>
            <br>
            <div class="text-center">
              <a href="blog.html" class="filled-button">Read More</a>
            </div>
            <br>
          </div>

          <div class="col-md-8">
            <section class='tabs-content'>
              <article id='tabs-1'>
                <img src="{% static 'assets/images/blog-image-1-940x460.jpg' %}" alt="">
                <h4><a href="blog-details.html">Lorem ipsum dolor sit amet, consectetur adipisicing.</a></h4>
                <p>Sed ut dolor in augue cursus ultrices. Vivamus mauris turpis, auctor vel facilisis in, tincidunt vel diam. Sed vitae scelerisque orci. Nunc non magna orci. Aliquam commodo mauris ante, quis posuere nibh vestibulum sit amet.</p>
              </article>
              <article id='tabs-2'>
                <img src="{% static 'assets/images/blog-image-2-940x460.jpg' %}" alt="">
                <h4><a href="blog-details.html">Mauris lobortis quam id dictum dignissim</a></h4>
                <p>Sed ut dolor in augue cursus ultrices. Vivamus mauris turpis, auctor vel facilisis in, tincidunt vel diam. Sed vitae scelerisque orci. Nunc non magna orci. Aliquam commodo mauris ante, quis posuere nibh vestibulum sit amet</p>
              </article>
            </section>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/josep/like_post.html
<!-- post_detail.html -->

{% if request.user.is_authenticated %}
  {% if request.user in post.like_set.all %}
    <form action="{% url 'like-post' post_id=post.id %}" method="post">
      {% csrf_token %}
      <button type="submit">Unlike</button>
    </form>
  {% else %}
    <form action="{% url 'like-post' post_id=post.id %}" method="post">
      {% csrf_token %}
      <button type="submit">Like</button>
    </form>
  {% endif %}
{% endif %}

<!-- Display like count -->
{{ post.like_set.count }}

templates/josep/location.html
{% load crispy_forms_tags %} 
    
    <!doctype html>
    <html lang="en">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <title>Location</title>
      </head>
      <body>
         <!-- navbar -->
         <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'location' %}">Map <span class="sr-only">(current)</span></a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>

          <div class="container">
            <div class="row" mt-4>
                <div class="col-md-10 offset-md-1">
                    {{ locations|safe}}
                </div>
            </div>
          </div>
          
         
        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    
       
      </body>
    </html>

templates/josep/video.html
{% load static %}
<html>
<body>


<video width="100%" height="700" autoplay muted playsinline loop>
   <source src="{% static 'assets/video/video_sapp2.mp4' %}" type="video/mp4">
   <source src="{% static 'assets/video/video_sapp2.mp4' %}" type="video/webm">
   Your browser does not support the video tag.
 </video>
 <!--Screen recorded will work, ajibola screen record worked-->
 
</body>
</html>